=== MATTYOneInc/AionClassic_2.4/dist/game/data/static_data/siege/siege_locations.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
	<xs:include schemaLocation="../zones/zones.xsd"/>
	<xs:include schemaLocation="../world_maps.xsd"/>
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="siege_locations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="siege_location" type="siegelocation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="siegelocation">
		<xs:sequence>
			<xs:element name="door_repair" type="DoorRepair" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="artifact_activation" type="ArtifactActivation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="siege_reward" type="SiegeReward" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
		<xs:attribute name="type" type="SiegeType" use="required"/>
		<xs:attribute name="world" type="xs:int" use="required"/>
		<xs:attribute name="name_id" type="xs:int"/>
		<xs:attribute name="fortress_dependency" type="DependencyList"/>
		<xs:attribute name="siege_duration" type="xs:int" use="optional" default="-1"/>
		<xs:attribute name="influence" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="buff_id" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="buff_idA" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="buff_idE" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="occupy_count" type="xs:int" use="optional" default="0"/>
	</xs:complexType>
	<xs:simpleType name="DependencyList">
		<xs:list itemType="xs:int"/>
	</xs:simpleType>
	<xs:simpleType name="SiegeType">
		<xs:restriction base="xs:string">
		    <xs:enumeration value="INDUN"/>
			<xs:enumeration value="FORTRESS"/>
			<xs:enumeration value="ARTIFACT"/>
			<xs:enumeration value="UNDERPASS"/>
			<xs:enumeration value="BOSSRAID_LIGHT"/>
			<xs:enumeration value="BOSSRAID_DARK"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="DoorRepair">
		<xs:attribute name="itemid" type="xs:int" use="optional" default="188030000"/>
		<xs:attribute name="repair_fee" type="xs:int"/>
		<xs:attribute name="repair_cooltime" type="xs:int" use="optional" default="-1"/>
	</xs:complexType>
	<xs:complexType name="ArtifactActivation">
		<xs:attribute name="itemid" type="xs:int" use="optional" default="188020000"/>
		<xs:attribute name="count" type="xs:int" use="optional" default="1"/>
		<xs:attribute name="skill" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="repeat_count" type="xs:int" use="optional" default="1"/>
		<xs:attribute name="repeat_interval" type="xs:int" use="optional" default="1"/>
		<xs:attribute name="cd" type="xs:int" use="optional" default="-1"/>
	</xs:complexType>
	<xs:complexType name="SiegeReward">
		<xs:attribute name="item_id" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="item_count" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="item_id2" type="xs:int" use="optional" default="0"/>
        <xs:attribute name="item_count2" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="item_id3" type="xs:int" use="optional" default="0"/>
        <xs:attribute name="item_count3" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="item_id4" type="xs:int" use="optional" default="0"/>
        <xs:attribute name="item_count4" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="item_id5" type="xs:int" use="optional" default="0"/>
        <xs:attribute name="item_count5" type="xs:int" use="optional" default="0"/>
        <xs:attribute name="ap_count" type="xs:int" use="optional" default="0"/>
        <xs:attribute name="exp_count" type="xs:int" use="optional" default="0"/>
        <xs:attribute name="kinah_count" type="xs:int" use="optional" default="0"/>
		<xs:attribute name="result" type="SiegeResult" use="optional"/>
	</xs:complexType>
	<xs:simpleType name="SiegeResult">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DEFENCE"/>
            <xs:enumeration value="OCCUPY"/>
            <xs:enumeration value="PROTECT"/>
            <xs:enumeration value="DEFENDER"/>
			<xs:enumeration value="EMPTY"/>
			<xs:enumeration value="FAIL"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== MATTYOneInc/AionClassic_2.4/dist/game/data/static_data/siege/siege_locations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Siege Locations
	Develop: ADev.Team
	https://aionpowerbook.com/powerbook/KR_Classic_-_Update_May_12th_2021
 -->
<siege_locations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="siege_locations.xsd">
	<siege_location id="0" type="UNDERPASS" world="210050000" name_id="730256"/>
	<siege_location id="0" type="UNDERPASS" world="220070000" name_id="730260"/>
	<siege_location id="0" type="UNDERPASS" world="210050000" name_id="730256"/>
	<siege_location id="0" type="UNDERPASS" world="220070000" name_id="730260"/>
	
	<siege_location id="1" type="INDUN" world="210040000" name_id="0"/>
	<siege_location id="2" type="INDUN" world="220040000" name_id="0"/>
	<siege_location id="3" type="INDUN" world="210020000" name_id="0"/>
	<siege_location id="3" type="INDUN" world="220020000" name_id="0"/>
	<siege_location id="4" type="INDUN" world="210040000" name_id="0"/>
	<siege_location id="5" type="INDUN" world="220040000" name_id="0"/>
	<siege_location id="6" type="INDUN" world="210060000" name_id="0"/>
	<siege_location id="7" type="INDUN" world="220050000" name_id="0"/>
	<siege_location id="8" type="INDUN" world="400010000" name_id="0"/>
	<siege_location id="8" type="INDUN" world="400010000" name_id="0"/>
	<siege_location id="9" type="INDUN" world="210040000" name_id="0"/>
	<siege_location id="9" type="INDUN" world="220040000" name_id="0"/>
	<siege_location id="9" type="INDUN" world="400010000" name_id="0"/>
	<siege_location id="18" type="INDUN" world="110010000" name_id="0"/>
	<siege_location id="18" type="INDUN" world="120010000" name_id="0"/>
	<siege_location id="25" type="INDUN" world="210040000" name_id="0"/>
	<siege_location id="45" type="INDUN" world="210040000" name_id="0"/>
	<siege_location id="45" type="INDUN" world="220040000" name_id="0"/>
	
	<!-- RESHANTA -->
	<!-- Divine Fortress -->
	<siege_location id="1011" type="FORTRESS" world="400010000" name_id="801109" siege_duration="7200" influence="14">
		<door_repair itemid="188030000" repair_fee="5" repair_cooltime="30"/>
		<artifact_activation itemid="188020000" count="1" skill="12078" repeat_count="1" repeat_interval="1" cd="7200"/>
		<siege_reward result="OCCUPY" item_id="186000163" item_count="80" item_id2="186000030" item_count2="80" item_id3="186000031" item_count3="80" item_id4="186000096" item_count4="80" item_id5="185000117" item_count5="1" ap_count="20000" kinah_count="1000000" exp_count="100000000"/>
		<siege_reward result="DEFENDER" item_id="186000163" item_count="40" item_id2="186000030" item_count2="40" item_id3="186000031" item_count3="40" item_id4="186000096" item_count4="40" ap_count="10000" kinah_count="500000" exp_count="50000000"/>
		<siege_reward result="FAIL" item_id="186000163" item_count="20" item_id2="186000030" item_count2="20" item_id3="186000031" item_count3="20" item_id4="186000096" item_count4="20" ap_count="5000" kinah_count="250000" exp_count="25000000"/>
	</siege_location>
	<siege_location id="1012" type="ARTIFACT" name_id="801755" world="400010000">
		<artifact_activation itemid="188020000" count="3" skill="12092" repeat_count="1" repeat_interval="1" cd="1800"/>
	</siege_location>
	<siege_location id="1013" type="ARTIFACT" name_id="801489" world="400010000">
		<artifact_activation itemid="188020000" count="2" skill="12079" repeat_count="1" repeat_interval="1" cd="2700"/>
	</siege_location>
	<siege_location id="1014" type="ARTIFACT" name_id="801489" world="400010000">
		<artifact_activation itemid="188020000" count="2" skill="12079" repeat_count="1" repeat_interval="1" cd="2700"/>
	</siege_location>
	<siege_location id="1015" type="ARTIFACT" name_id="801491" world="400010000">
		<artifact_activation itemid="188020000" count="1" skill="12089" repeat_count="6" repeat_interval="9" cd="900"/>
	</siege_location>
	<siege_location id="1016" type="ARTIFACT" name_id="801495" world="400010000">
		<artifact_activation itemid="188020000" count="2" skill="12081" repeat_count="1" repeat_interval="1" cd="2700"/>
	</siege_location>
	<siege_location id="1017" type="ARTIFACT" name_id="801501" world="400010000">
		<artifact_activation itemid="188020000" count="3" skill="12090" repeat_count="5" repeat_interval="3" cd="2700"/>
	</siege_location>
	<siege_location id="1018" type="ARTIFACT" name_id="801501" world="400010000">
		<artifact_activation itemid="188020000" count="3" skill="12090" repeat_count="5" repeat_interval="3" cd="2700"/>
	</siege_location>
	<siege_location id="1019" type="ARTIFACT" name_id="801501" world="400010000">
		<artifact_activation itemid="188020000" count="3" skill="12090" repeat_count="5" repeat_interval="3" cd="2700"/>
	</siege_location>
	<siege_location id="1020" type="ARTIFACT" name_id="801497" world="400010000">
		<artifact_activation itemid="188020000" count="1" skill="12087" repeat_count="1" repeat_interval="1" cd="900"/>
	</siege_location>
	<!-- Siel's Western Fortress -->
	<siege_location id="1131" type="FORTRESS" world="400010000" name_id="801119" siege_duration="1800" influence="8">
		<door_repair itemid="188030000" repair_fee="5" repair_cooltime="30"/>
		<artifact_activation itemid="188020000" count="1" skill="12070" repeat_count="1" repeat_interval="1" cd="3600"/>
		<siege_reward result="OCCUPY" item_id="186000163" item_count="80" item_id2="186000030" item_count2="80" item_id3="186000031" item_count3="80" item_id4="186000096" item_count4="80" ap_count="20000" kinah_count="1000000" exp_count="100000000"/>
		<siege_reward result="DEFENDER" item_id="186000163" item_count="40" item_id2="186000030" item_count2="40" item_id3="186000031" item_count3="40" item_id4="186000096" item_count4="40" ap_count="10000" kinah_count="500000" exp_count="50000000"/>
		<siege_reward result="FAIL" item_id="186000163" item_count="20" item_id2="186000030" item_count2="20" item_id3="186000031" item_count3="20" item_id4="186000096" item_count4="20" ap_count="5000" kinah_count="250000" exp_count="25000000"/>
	</siege_location>
	<!-- Siel's Eastern Fortress -->
	<siege_location id="1132" type="FORTRESS" world="400010000" name_id="801131" siege_duration="1800" influence="8">
		<door_repair itemid="188030000" repair_fee="5" repair_cooltime="30"/>
		<artifact_activation itemid="188020000" count="1" skill="12071" repeat_count="1" repeat_interval="1" cd="3600"/>
		<siege_reward result="OCCUPY" item_id="186000163" item_count="80" item_id2="186000030" item_count2="80" item_id3="186000031" item_count3="80" item_id4="186000096" item_count4="80" ap_count="20000" kinah_count="1000000" exp_count="100000000"/>
		<siege_reward result="DEFENDER" item_id="186000163" item_count="40" item_id2="186000030" item_count2="40" item_id3="186000031" item_count3="40" item_id4="186000096" item_count4="40" ap_count="10000" kinah_count="500000" exp_count="50000000"/>
		<siege_reward result="FAIL" item_id="186000163" item_count="20" item_id2="186000030" item_count2="20" item_id3="186000031" item_count3="20" item_id4="186000096" item_count4="20" ap_count="5000" kinah_count="250000" exp_count="25000000"/>
	</siege_location>
	<siege_location id="1133" type="ARTIFACT" name_id="801489" world="400010000">
		<artifact_activation itemid="188020000" count="2" skill="12043" repeat_count="1" repeat_interval="1" cd="2700"/>
	</siege_location>
	<siege_location id="1134" type="ARTIFACT" name_id="801489" world="400010000">
		<artifact_activation itemid="188020000" count="2" skill="12043" repeat_count="1" repeat_interval="1" cd="2700"/>
	</siege_location>
	<siege_location id="1135" type="ARTIFACT" name_id="801487" world="400010000">
		<artifact_activation itemid="188020000" count="1" skill="12042" repeat_count="1" repeat_interval="1" cd="900"/>
	</siege_location>
	<!-- Sulfur Fortress -->
	<siege_location id="1141" type="FORTRESS" world="400010000" name_id="801143" siege_duration="1800" influence="8">
		<door_repair itemid="188030000" repair_fee="5" repair_cooltime="30"/>
		<artifact_activation itemid="188020000" count="1" skill="12072" repeat_count="1" repeat_interval="1" cd="3600"/>
		<siege_reward result="OCCUPY" item_id="186000163" item_count="80" item_id2="186000030" item_count2="80" item_id3="186000031" item_count3="80" item_id4="186000096" item_count4="80" ap_count="20000" kinah_count="1000000" exp_count="100000000"/>
		<siege_reward result="DEFENDER" item_id="186000163" item_count="40" item_id2="186000030" item_count2="40" item_id3="186000031" item_count3="40" item_id4="186000096" item_count4="40" ap_count="10000" kinah_count="500000" exp_count="50000000"/>
		<siege_reward result="FAIL" item_id="186000163" item_count="20" item_id2="186000030" item_count2="20" item_id3="186000031" item_count3="20" item_id4="186000096" item_count4="20" ap_count="5000" kinah_count="250000" exp_count="25000000"/>
	</siege_location>
	<siege_location id="1142" type="ARTIFACT" name_id="801489" world="400010000">
		<artifact_activation itemid="188020000" count="2" skill="12043" repeat_count="1" repeat_interval="1" cd="2700"/>
	</siege_location>
	<siege_location id="1143" type="ARTIFACT" name_id="801487" world="400010000">
		<artifact_activation itemid="188020000" count="1" skill="12042" repeat_count="1" repeat_interval="1" cd="900"/>
	</siege_location>
	<siege_location id="1144" type="ARTIFACT" name_id="801493" world="400010000">
		<artifact_activation itemid="188020000" count="1" skill="12045" repeat_count="1" repeat_interval="1" cd="900"/>
	</siege_location>
	<siege_location id="1145" type="ARTIFACT" name_id="801759" world="400010000">
		<artifact_activation itemid="188020000" count="2" skill="12057" repeat_count="1" repeat_interval="1" cd="2700"/>
	</siege_location>
	<siege_location id="1146" type="ARTIFACT" name_id="801245" world="400010000">
		<artifact_activation itemid="188020000" count="2" skill="12085" repeat_count="1" repeat_interval="1" cd="2700"/>
	</siege_location>
	<!-- Roah Fortress -->
	<siege_location id="1211" type="FORTRESS" world="400010000" name_id="801829" siege_duration="2700" influence="10">
