=== MATTYOneInc/AionClassic_2.4/dist/game/data/static_data/battle_pass/battlepass_quests.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../global_types.xsd"/>
    <xs:element name="battlepass_quests">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="battlepass_quest" type="BattlePassQuestTemplate" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="BattlePassQuestTemplate">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="type" type="BattleQuestType"/>
        <xs:attribute name="pass_id" type="xs:int"/>
        <xs:attribute name="action_id" type="xs:int"/>
        <xs:attribute name="active" type="xs:boolean"/>
        <xs:attribute name="min_level" type="xs:int"/>
        <xs:attribute name="max_level" type="xs:int"/>
        <xs:attribute name="complete_exp" type="xs:int"/>
        <xs:attribute name="race" type="Race"/>
        <xs:attribute name="start" type="xs:dateTime" use="required"/>
        <xs:attribute name="end" type="xs:dateTime" use="required"/>
    </xs:complexType>
    <xs:simpleType name="BattleQuestType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DAILY"/>
            <xs:enumeration value="WEEKLY"/>
            <xs:enumeration value="SEASON"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== MATTYOneInc/AionClassic_2.4/dist/game/data/static_data/battle_pass/battlepass_quests.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
	Daeva Pass [Aion Classic]
	Develop: ADev.Team
 -->
<battlepass_quests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="battlepass_quests.xsd">
    <battlepass_quest id="573" type="DAILY" pass_id="32001" action_id="573" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="15"/>
    <battlepass_quest id="574" type="DAILY" pass_id="32001" action_id="574" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="15"/>
    <battlepass_quest id="575" type="DAILY" pass_id="32001" action_id="575" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="15"/>
    <battlepass_quest id="576" type="DAILY" pass_id="32001" action_id="576" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="10"/>
    <battlepass_quest id="577" type="DAILY" pass_id="32001" action_id="577" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="10"/>
    <battlepass_quest id="578" type="WEEKLY" pass_id="32001" action_id="578" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="70"/>
    <battlepass_quest id="579" type="WEEKLY" pass_id="32001" action_id="579" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="80"/>
    <battlepass_quest id="580" type="WEEKLY" pass_id="32001" action_id="580" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="70"/>
    <battlepass_quest id="581" type="WEEKLY" pass_id="32001" action_id="581" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="80"/>
    <battlepass_quest id="582" type="WEEKLY" pass_id="32001" action_id="582" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="70"/>
    <battlepass_quest id="583" type="WEEKLY" pass_id="32001" action_id="583" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="70"/>
    <battlepass_quest id="584" type="WEEKLY" pass_id="32001" action_id="584" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="80"/>
    <battlepass_quest id="585" type="WEEKLY" pass_id="32001" action_id="585" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="80"/>
    <battlepass_quest id="586" type="SEASON" pass_id="32001" action_id="586" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="587" type="SEASON" pass_id="32001" action_id="587" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="588" type="SEASON" pass_id="32001" action_id="588" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="589" type="SEASON" pass_id="32001" action_id="589" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="590" type="SEASON" pass_id="32001" action_id="590" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="591" type="SEASON" pass_id="32001" action_id="591" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="200"/>
    <battlepass_quest id="592" type="SEASON" pass_id="32001" action_id="592" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="593" type="SEASON" pass_id="32001" action_id="593" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="594" type="SEASON" pass_id="32001" action_id="594" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="595" type="SEASON" pass_id="32001" action_id="595" active="1" start="2022-05-25T09:00:00+00:00" end="2025-12-08T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="100"/>
    <battlepass_quest id="961" type="DAILY" pass_id="42004" action_id="961" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="15"/>
    <battlepass_quest id="962" type="DAILY" pass_id="42004" action_id="962" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="15"/>
    <battlepass_quest id="963" type="DAILY" pass_id="42004" action_id="963" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="15"/>
    <battlepass_quest id="964" type="DAILY" pass_id="42004" action_id="964" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="10"/>
    <battlepass_quest id="965" type="DAILY" pass_id="42004" action_id="965" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="10"/>
    <battlepass_quest id="966" type="WEEKLY" pass_id="42004" action_id="966" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="80"/>
    <battlepass_quest id="967" type="WEEKLY" pass_id="42004" action_id="967" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="80"/>
    <battlepass_quest id="968" type="WEEKLY" pass_id="42004" action_id="968" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="80"/>
    <battlepass_quest id="969" type="WEEKLY" pass_id="42004" action_id="969" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="80"/>
    <battlepass_quest id="970" type="WEEKLY" pass_id="42004" action_id="970" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="80"/>
    <battlepass_quest id="971" type="SEASON" pass_id="42004" action_id="971" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="200"/>
    <battlepass_quest id="972" type="SEASON" pass_id="42004" action_id="972" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="100"/>
    <battlepass_quest id="973" type="SEASON" pass_id="42004" action_id="973" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="100"/>
    <battlepass_quest id="974" type="SEASON" pass_id="42004" action_id="974" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="975" type="SEASON" pass_id="42004" action_id="975" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="200"/>
    <battlepass_quest id="976" type="SEASON" pass_id="42004" action_id="976" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="977" type="SEASON" pass_id="42004" action_id="977" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="100"/>
    <battlepass_quest id="978" type="SEASON" pass_id="42004" action_id="978" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="200"/>
    <battlepass_quest id="979" type="SEASON" pass_id="42004" action_id="979" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="980" type="SEASON" pass_id="42004" action_id="980" active="1" start="2022-11-23T09:00:00+00:00" end="2023-12-20T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="150"/>
    <battlepass_quest id="1057" type="DAILY" pass_id="2020" action_id="1057" active="1" start="2023-01-18T09:00:00+00:00" end="2023-02-15T09:00:00+00:00" min_level="1" max_level="55" race="PC_ALL" complete_exp="15"/>
