=== MATTYOneInc/AionClassic_2.4/dist/game/data/static_data/guild/guild_growths.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../global_types.xsd"/>
    <xs:include schemaLocation="../import.xsd"/>
    <xs:element name="guild_growths">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="guild_growth" type="GuildGrowthTemplate" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="GuildGrowthTemplate">
        <xs:attribute name="level" type="xs:int" use="optional"/>
        <xs:attribute name="guild_exp" type="xs:int" use="required"/>
    </xs:complexType>
</xs:schema>

=== MATTYOneInc/AionClassic_2.4/dist/game/data/static_data/guild/guild_growths.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<guild_growths xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="guild_growths.xsd">
    <guild_growth level="1" guild_exp="0"/>
    <guild_growth level="2" guild_exp="50000"/>
    <guild_growth level="3" guild_exp="50000"/>
    <guild_growth level="4" guild_exp="50000"/>
    <guild_growth level="5" guild_exp="50000"/>
    <guild_growth level="6" guild_exp="55000"/>
    <guild_growth level="7" guild_exp="60000"/>
    <guild_growth level="8" guild_exp="65000"/>
    <guild_growth level="9" guild_exp="70000"/>
    <guild_growth level="10" guild_exp="70000"/>
    <guild_growth level="11" guild_exp="75000"/>
    <guild_growth level="12" guild_exp="75000"/>
    <guild_growth level="13" guild_exp="75000"/>
    <guild_growth level="14" guild_exp="75000"/>
    <guild_growth level="15" guild_exp="85000"/>
    <guild_growth level="16" guild_exp="85500"/>
    <guild_growth level="17" guild_exp="85500"/>
    <guild_growth level="18" guild_exp="85500"/>
    <guild_growth level="19" guild_exp="85500"/>
    <guild_growth level="20" guild_exp="86000"/>
    <guild_growth level="21" guild_exp="86000"/>
    <guild_growth level="22" guild_exp="86000"/>
    <guild_growth level="23" guild_exp="86000"/>
    <guild_growth level="24" guild_exp="86000"/>
    <guild_growth level="25" guild_exp="86000"/>
    <guild_growth level="26" guild_exp="86000"/>
    <guild_growth level="27" guild_exp="86000"/>
    <guild_growth level="28" guild_exp="86000"/>
    <guild_growth level="29" guild_exp="86000"/>
    <guild_growth level="30" guild_exp="86500"/>
    <guild_growth level="31" guild_exp="86500"/>
    <guild_growth level="32" guild_exp="86500"/>
    <guild_growth level="33" guild_exp="86500"/>
    <guild_growth level="34" guild_exp="86500"/>
    <guild_growth level="35" guild_exp="86500"/>
    <guild_growth level="36" guild_exp="86500"/>
    <guild_growth level="37" guild_exp="86500"/>
    <guild_growth level="38" guild_exp="86500"/>
    <guild_growth level="39" guild_exp="86500"/>
    <guild_growth level="40" guild_exp="87000"/>
    <guild_growth level="41" guild_exp="87000"/>
    <guild_growth level="42" guild_exp="87000"/>
    <guild_growth level="43" guild_exp="87000"/>
    <guild_growth level="44" guild_exp="87000"/>
    <guild_growth level="45" guild_exp="87000"/>
    <guild_growth level="46" guild_exp="87000"/>
    <guild_growth level="47" guild_exp="87000"/>
    <guild_growth level="48" guild_exp="87000"/>
    <guild_growth level="49" guild_exp="87000"/>
    <guild_growth level="50" guild_exp="87500"/>
    <guild_growth level="51" guild_exp="87500"/>
    <guild_growth level="52" guild_exp="87500"/>
    <guild_growth level="53" guild_exp="87500"/>
    <guild_growth level="54" guild_exp="87500"/>
    <guild_growth level="55" guild_exp="87500"/>
    <guild_growth level="56" guild_exp="87500"/>
    <guild_growth level="57" guild_exp="87500"/>
    <guild_growth level="58" guild_exp="87500"/>
    <guild_growth level="59" guild_exp="87500"/>
    <guild_growth level="60" guild_exp="90000"/>
    <guild_growth level="61" guild_exp="90000"/>
    <guild_growth level="62" guild_exp="90000"/>
    <guild_growth level="63" guild_exp="90000"/>
    <guild_growth level="64" guild_exp="90000"/>
    <guild_growth level="65" guild_exp="90000"/>
    <guild_growth level="66" guild_exp="90000"/>
    <guild_growth level="67" guild_exp="90000"/>
    <guild_growth level="68" guild_exp="90000"/>
    <guild_growth level="69" guild_exp="90000"/>
    <guild_growth level="70" guild_exp="90000"/>
    <guild_growth level="71" guild_exp="90000"/>
    <guild_growth level="72" guild_exp="90000"/>
    <guild_growth level="73" guild_exp="90000"/>
    <guild_growth level="74" guild_exp="90000"/>
    <guild_growth level="75" guild_exp="90000"/>
    <guild_growth level="76" guild_exp="90000"/>
    <guild_growth level="77" guild_exp="90000"/>
    <guild_growth level="78" guild_exp="90000"/>
    <guild_growth level="79" guild_exp="90000"/>
    <guild_growth level="80" guild_exp="100000"/>
    <guild_growth level="81" guild_exp="100000"/>
    <guild_growth level="82" guild_exp="100000"/>
    <guild_growth level="83" guild_exp="100000"/>
    <guild_growth level="84" guild_exp="100000"/>
    <guild_growth level="85" guild_exp="100000"/>
    <guild_growth level="86" guild_exp="100000"/>
    <guild_growth level="87" guild_exp="100000"/>
    <guild_growth level="88" guild_exp="100000"/>
    <guild_growth level="89" guild_exp="100000"/>
    <guild_growth level="90" guild_exp="150000"/>
    <guild_growth level="91" guild_exp="150000"/>
    <guild_growth level="92" guild_exp="150000"/>
    <guild_growth level="93" guild_exp="150000"/>
    <guild_growth level="94" guild_exp="150000"/>
    <guild_growth level="95" guild_exp="150000"/>
    <guild_growth level="96" guild_exp="150000"/>
    <guild_growth level="97" guild_exp="150000"/>
    <guild_growth level="98" guild_exp="150000"/>
    <guild_growth level="99" guild_exp="150000"/>
    <guild_growth level="100" guild_exp="250000"/>
</guild_growths>
