=== MATTYOneInc/AionClassic_2.4/dist/game/data/static_data/guild/guild_achievement_templates.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../global_types.xsd"/>
    <xs:include schemaLocation="../import.xsd"/>
    <xs:include schemaLocation="../battle_pass/battlepass_actions.xsd"/>
    <xs:element name="guild_achievement_templates">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="guild_achievement_template" type="GuildAchievement" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="GuildAchievement">
        <xs:sequence>
            <xs:element name="guild_action" type="GuildAction" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="guild_achievement_reward" type="GuildAchievementReward" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="min_level" type="xs:int" use="required"/>
        <xs:attribute name="max_level" type="xs:int" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="max_stage" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="GuildAction">
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="GuildAchievementReward">
        <xs:attribute name="completecount" type="xs:int" use="required"/>
        <xs:attribute name="exp" type="xs:int" use="optional"/>
        <xs:attribute name="essence_amount" type="xs:int" use="optional"/>
        <xs:attribute name="essence_piece_amount" type="xs:int" use="optional"/>
    </xs:complexType>
</xs:schema>

=== MATTYOneInc/AionClassic_2.4/dist/game/data/static_data/guild/guild_achievement_templates.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<guild_achievement_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="guild_achievement_templates.xsd">
   <guild_achievement_template id="4" name="Region_Daily_01" min_level="1" max_level="100" type="DAILY" max_stage="2">
       <guild_action id="100012"/>
       <guild_action id="100013"/>
       <guild_action id="100014"/>
       <guild_action id="100015"/>
       <guild_action id="100016"/>
       <guild_action id="100017"/>
       <guild_action id="100018"/>
       <guild_action id="100019"/>
       <guild_action id="100020"/>
       <guild_achievement_reward completecount="3" exp="114" essence_amount="0" essence_piece_amount="2"/>
       <guild_achievement_reward completecount="2" exp="171" essence_amount="0" essence_piece_amount="2"/>
   </guild_achievement_template>
   <guild_achievement_template id="5" name="Region_Weekly_01" min_level="1" max_level="100" type="WEEKLY" max_stage="2">
       <guild_action id="100021"/>
       <guild_action id="100022"/>
       <guild_action id="100023"/>
       <guild_action id="100024"/>
       <guild_action id="100025"/>
       <guild_action id="100026"/>
       <guild_action id="100027"/>
       <guild_action id="100028"/>
       <guild_action id="100029"/>
       <guild_action id="100030"/>
       <guild_action id="100031"/>
       <guild_action id="100032"/>
       <guild_action id="100033"/>
       <guild_action id="100034"/>
       <guild_action id="100035"/>
       <guild_action id="100036"/>
       <guild_action id="100037"/>
       <guild_action id="100038"/>
       <guild_action id="100039"/>
       <guild_achievement_reward completecount="5" exp="1200" essence_amount="0" essence_piece_amount="11"/>
       <guild_achievement_reward completecount="5" exp="1800" essence_amount="0" essence_piece_amount="17"/>
   </guild_achievement_template>
</guild_achievement_templates>
